Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$scanner = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\bootstrap_scan_credentials.ps1'))
if (-not (Test-Path -LiteralPath $scanner -PathType Leaf)) { Write-Output 'CONTRACT_RED scanner_missing'; exit 1 }
function Stop-Contract { param([string]$Code) Write-Output "CONTRACT_FAIL $Code"; exit 1 }
function Invoke-Scanner { param([string[]]$Arguments) $output = @(& (Join-Path $PSHOME 'pwsh.exe') -NoProfile -File $scanner @Arguments 2>&1 | ForEach-Object { $_.ToString() }); [pscustomobject]@{ ExitCode = $LASTEXITCODE; Output = $output } }
function Assert-ExactResult {
    param($Result, [int]$ExitCode, [string[]]$Output, [string]$Code)
    if ($Result.ExitCode -ne $ExitCode -or $Result.Output.Count -ne $Output.Count) { Stop-Contract $Code }
    for ($i = 0; $i -lt $Output.Count; $i++) { if ($Result.Output[$i] -cne $Output[$i]) { Stop-Contract $Code } }
}
function Assert-OperationalFailure {
    param($Result, [string]$ExpectedCode, [string]$ExpectedSource, [string]$ExpectedPath, [string]$Code)
    if ($Result.ExitCode -ne 3 -or $Result.Output.Count -ne 1) { Stop-Contract $Code }
    try { $record = $Result.Output[0] | ConvertFrom-Json -ErrorAction Stop } catch { Stop-Contract $Code }
    if ($record.code -cne $ExpectedCode) { Stop-Contract $Code }
    foreach ($entry in @{ source = $ExpectedSource; path = $ExpectedPath }.GetEnumerator()) { $property = $record.PSObject.Properties[$entry.Key]; if ($entry.Value) { if (-not $property -or $property.Value -cne $entry.Value) { Stop-Contract $Code } } elseif ($property) { Stop-Contract $Code } }
    foreach ($name in $record.PSObject.Properties.Name) { if ($name -notin @('source', 'path', 'code')) { Stop-Contract $Code } }
}
function Assert-DirectCase {
    param([string]$Name, [string]$Text, [string]$Rule, [bool]$Match, [Text.Encoding]$Encoding)
    $file = "$Name.txt"; [IO.File]::WriteAllText((Join-Path (Get-Location).ProviderPath $file), $Text, $Encoding)
    if ($Match) { Assert-ExactResult (Invoke-Scanner @('-Path', $file)) 2 @("{`"source`":`"path`",`"path`":`"$file`",`"rule`":`"$Rule`"}") $Name } else { Assert-ExactResult (Invoke-Scanner @('-Path', $file)) 0 @('CREDENTIAL_SCAN_PASS files=1') $Name }
}
function Set-FakeGit {
    param([string[]]$Paths, [string[]]$Rows, [hashtable]$Blobs, [string]$Case = 'ok')
    $env:FG_PATHS = $Paths -join '|'; $env:FG_ROWS = $Rows -join '|'; $env:FG_CASE = $Case
    Get-ChildItem -LiteralPath $blobDir -File | Remove-Item -Force
    foreach ($entry in $Blobs.GetEnumerator()) { [IO.File]::WriteAllBytes((Join-Path $blobDir ($entry.Key + '.bin')), [byte[]]$entry.Value) }
}
$sandbox = Join-Path ([IO.Path]::GetTempPath()) ('projectb-f01s3-' + [guid]::NewGuid().ToString('N')); [IO.Directory]::CreateDirectory($sandbox) | Out-Null; $oldPath=$env:PATH
try {
 Push-Location $sandbox
 try {
    $utf8 = [Text.UTF8Encoding]::new($false); [IO.File]::WriteAllText((Join-Path $sandbox 'clean.txt'), 'ordinary public text', $utf8); [IO.File]::WriteAllText((Join-Path $sandbox 'other.txt'), 'more public text', $utf8)
    [IO.File]::WriteAllBytes((Join-Path $sandbox 'invalid.txt'), [byte[]](0xC3, 0x28)); [IO.File]::WriteAllBytes((Join-Path $sandbox 'nul.txt'), [byte[]](0x61, 0x00, 0x62)); [IO.File]::WriteAllBytes((Join-Path $sandbox 'bom.txt'), [byte[]](0xEF, 0xBB, 0xBF, 0x61)); [IO.File]::WriteAllBytes((Join-Path $sandbox 'skip.png'), [byte[]](0x00, 0x61, 0x00)); [IO.File]::WriteAllText((Join-Path $sandbox 'replacement.txt'), "bad$([char]0xFFFD)text", $utf8); [IO.File]::WriteAllText((Join-Path $sandbox 'unknown.svg'), 'ordinary public text', $utf8); [IO.Directory]::CreateDirectory((Join-Path $sandbox 'folder')) | Out-Null
    $utf16le = [Text.UnicodeEncoding]::new($false, $true, $true); $utf16be = [Text.UnicodeEncoding]::new($true, $true, $true); foreach ($case in @(@('utf16le.txt', $utf16le), @('utf16be.txt', $utf16be))) { [IO.File]::WriteAllBytes((Join-Path $sandbox $case[0]), [byte[]]($case[1].GetPreamble() + $case[1].GetBytes('ordinary public text'))) }
    $utf32le = [Text.UTF32Encoding]::new($false, $true, $true); $utf32be = [Text.UTF32Encoding]::new($true, $true, $true); foreach ($case in @(@('utf32le.txt', $utf32le), @('utf32be.txt', $utf32be))) { [IO.File]::WriteAllBytes((Join-Path $sandbox $case[0]), [byte[]]($case[1].GetPreamble() + $case[1].GetBytes('ordinary public text'))) }
    Assert-OperationalFailure (Invoke-Scanner @()) 'usage_missing_scope' 'path' '' 'usage_missing_scope'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\missing.txt')) 'read_failed' 'path' 'missing.txt' 'missing_read'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\folder')) 'read_failed' 'path' 'folder' 'non_file_read'
    Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\invalid.txt')) 'decode_failed' 'path' 'invalid.txt' 'invalid_utf8'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\nul.txt')) 'nul_unmarked' 'path' 'nul.txt' 'nul_rejected'; Assert-ExactResult (Invoke-Scanner @('-Path', '.\bom.txt')) 0 @('CREDENTIAL_SCAN_PASS files=1') 'bom_accepted'; Assert-ExactResult (Invoke-Scanner @('-Path', '.\utf16le.txt')) 0 @('CREDENTIAL_SCAN_PASS files=1') 'utf16le_accepted'; Assert-ExactResult (Invoke-Scanner @('-Path', '.\utf16be.txt')) 0 @('CREDENTIAL_SCAN_PASS files=1') 'utf16be_accepted'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\utf32le.txt')) 'decode_failed' 'path' 'utf32le.txt' 'utf32le_rejected'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\utf32be.txt')) 'decode_failed' 'path' 'utf32be.txt' 'utf32be_rejected'; Assert-ExactResult (Invoke-Scanner @('-Path', '.\skip.png')) 0 @('CREDENTIAL_SCAN_PASS files=0') 'binary_skip'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\replacement.txt')) 'decode_failed' 'path' 'replacement.txt' 'replacement_rejected'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\unknown.svg')) 'unsupported_file_type' 'path' 'unknown.svg' 'unknown_extension'
    Assert-ExactResult (Invoke-Scanner @('-Path', '.\clean.txt')) 0 @('CREDENTIAL_SCAN_PASS files=1') 'clean_receipt'; Assert-OperationalFailure (Invoke-Scanner @('-Path', '.\clean.txt', '.\other.txt')) 'usage_missing_scope' 'path' '' 'single_path_only'; Write-Output 'usage_and_output'
    [IO.Directory]::CreateDirectory((Join-Path $sandbox 'nested')) | Out-Null; $fragmentOne = 'sk-' + ('A' * 10); $fragmentTwo = 'B' * 10; $positive = $fragmentOne + $fragmentTwo; [IO.File]::WriteAllText((Join-Path $sandbox 'nested\case.txt'), "[$positive]`n$positive", $utf8)
    Assert-ExactResult (Invoke-Scanner @('-Path', '.\nested\case.txt')) 2 @('{"source":"path","path":"nested/case.txt","rule":"provider_api_key"}') 'provider_match_unique'; Assert-ExactResult (Invoke-Scanner @('-Path', '.\.\nested\case.txt')) 2 @('{"source":"path","path":"./nested/case.txt","rule":"provider_api_key"}') 'provider_double_prefix_receipt'
    $maximum = 's' + 'k-' + ('A1_-' * 50); Assert-DirectCase 'provider_maximum_alphabet' $maximum 'provider_api_key' $true $utf8; $maximal = 's' + 'k-' + ('E' * 200); Assert-DirectCase 'provider_boundaries' ("x$positive`n${maximal}_`n" + ('s' + 'k-' + ('C' * 19)) + "`n" + ('s' + 'k-' + ('D' * 201))) 'provider_api_key' $false $utf8; Write-Output 'provider_rule'
    $github = 'gh' + 'p_' + ('A' * 20); $aws = 'AK' + 'IA' + ('A0' * 8); $google = 'AI' + 'za' + ('a_-' * 11) + 'aa'; $slack = 'xo' + 'xb-' + ('A-' * 5); $private = '-----' + 'BEGIN ' + 'RSA ' + 'PRIVATE KEY' + '-----'
    [IO.File]::WriteAllText((Join-Path $sandbox 'direct.txt'), "$github`n$github`n$aws`n$google`n$slack`n$private", $utf8); $directExpected = @('{"source":"path","path":"direct.txt","rule":"aws_access_key"}','{"source":"path","path":"direct.txt","rule":"github_token"}','{"source":"path","path":"direct.txt","rule":"google_api_key"}','{"source":"path","path":"direct.txt","rule":"private_key"}','{"source":"path","path":"direct.txt","rule":"slack_token"}'); Assert-ExactResult (Invoke-Scanner @('-Path', '.\direct.txt')) 2 $directExpected 'direct_rules_and_order'
    Assert-DirectCase 'github_max' ('gh' + 'r_' + ('Z' * 255)) 'github_token' $true $utf8; foreach ($prefix in @('gho_','ghu_','ghs_')) { Assert-DirectCase "github_$prefix" ($prefix + ('Z' * 20)) 'github_token' $true $utf8 }; Assert-DirectCase 'github_short' ('gho_' + ('Z' * 19)) 'github_token' $false $utf8; Assert-DirectCase 'github_long' ('ghu_' + ('Z' * 256)) 'github_token' $false $utf8; Assert-DirectCase 'github_neighbors' ('xghs_' + ('Z' * 20) + "`n" + ('ghp_' + ('Z' * 20) + '_')) 'github_token' $false $utf8
    Assert-DirectCase 'aws_short' ('ASIA' + ('Z' * 15)) 'aws_access_key' $false $utf8; Assert-DirectCase 'aws_long' ('ASIA' + ('Z' * 17)) 'aws_access_key' $false $utf8; Assert-DirectCase 'aws_neighbors' (('ASIA' + ('Z' * 16) + '_') + "`n" + ('xAKIA' + ('Z' * 16))) 'aws_access_key' $false $utf8; Assert-DirectCase 'aws_asia' ('ASIA' + ('Z' * 16)) 'aws_access_key' $true $utf8
    Assert-DirectCase 'google_short' ('AIza' + ('Z' * 34)) 'google_api_key' $false $utf8; Assert-DirectCase 'google_long' ('AIza' + ('Z' * 36)) 'google_api_key' $false $utf8; Assert-DirectCase 'google_neighbors' (('xAIza' + ('Z' * 35)) + "`n" + ('AIza' + ('Z' * 35) + '_')) 'google_api_key' $false $utf8
    Assert-DirectCase 'slack_max' ('xoxs-' + ('Z-' * 100)) 'slack_token' $true $utf8; foreach ($prefix in @('xoxp-','xoxa-','xoxr-')) { Assert-DirectCase "slack_$prefix" ($prefix + ('Z' * 10)) 'slack_token' $true $utf8 }; Assert-DirectCase 'slack_short' ('xoxp-' + ('Z' * 9)) 'slack_token' $false $utf8; Assert-DirectCase 'slack_long' ('xoxa-' + ('Z' * 201)) 'slack_token' $false $utf8; Assert-DirectCase 'slack_neighbors' (('xoxr-' + ('Z' * 10) + '_') + "`n" + ('xxoxb-' + ('Z' * 10))) 'slack_token' $false $utf8
    foreach ($prefix in @('','EC ','DSA ','OPENSSH ')) { Assert-DirectCase "private_$($prefix.Length)" ('-----' + 'BEGIN ' + $prefix + 'PRIVATE KEY' + '-----') 'private_key' $true $utf8 }; Write-Output 'direct_rules_and_order'
    foreach ($owned in @($scanner,$PSCommandPath)) { Assert-ExactResult (Invoke-Scanner @('-Path',$owned)) 0 @('CREDENTIAL_SCAN_PASS files=1') 'artifact_direct_safety' }; Write-Output 'artifact_direct_safety'
    foreach ($name in @('api_key','api-key','apikey','access_token','auth_token','client_secret','password','passwd','secret','token')) { Assert-DirectCase "assignment_name_$name" ("#$($name.ToUpperInvariant()) `t: `t" + ('q' * 12)) 'assignment_secret' $true $utf8 }
    Assert-DirectCase 'assignment_equals_alphabet' ('api' + '_key=Ab0_./+=:@-') 'assignment_secret' $true $utf8; Assert-DirectCase 'assignment_left_boundary' ('xapi' + '_key=' + ('q' * 12)) 'assignment_secret' $false $utf8; foreach ($case in @(@('unquoted_min',8,$true),@('unquoted_short',7,$false),@('unquoted_max',512,$true),@('unquoted_long',513,$false))) { Assert-DirectCase "assignment_$($case[0])" ('pass' + 'wd=' + ('q' * $case[1])) 'assignment_secret' $case[2] $utf8 }
    Assert-DirectCase 'assignment_double_escape' (('pass' + 'word=') + '"abc\"d\\ef"') 'assignment_secret' $true $utf8; Assert-DirectCase 'assignment_single_escape' (('pass' + 'word=') + "'abc\'d\\ef'") 'assignment_secret' $true $utf8; foreach ($case in @(@('quote_short',7,$false),@('quote_max',512,$true),@('quote_long',513,$false))) { Assert-DirectCase "assignment_$($case[0])" (('pass' + 'word="') + ('q' * $case[1]) + '"') 'assignment_secret' $case[2] $utf8 }
    $supplementary = [char]::ConvertFromUtf32(0x1F600); Assert-DirectCase 'assignment_unicode_max' (('pass' + 'word="') + ($supplementary * 512) + '"') 'assignment_secret' $true $utf8; Assert-DirectCase 'assignment_unicode_long' (('pass' + 'word="') + ($supplementary * 513) + '"') 'assignment_secret' $false $utf8; Assert-DirectCase 'assignment_bad_escape' (('pass' + 'word="') + 'abc\ndefgh"') 'assignment_secret' $false $utf8; Assert-DirectCase 'assignment_mismatch' (('pass' + 'word=') + "`"abcdefgh'") 'assignment_secret' $false $utf8; Assert-DirectCase 'assignment_newline' (('pass' + 'word=') + "`"abcd`nefgh`"") 'assignment_secret' $false $utf8
    $asciiPad = ([char]0x09)+([char]0x0B)+([char]0x0C)+' '; foreach ($safe in @('EXAMPLE','PLACEHOLDER','ChangeMe','NOT-SET','NONE','NULL','REDACTED','<hidden>','$LONG_ENV_VAR','${LONG_ENV_VAR}','[value ReDaCtEd now]')) { Assert-DirectCase "assignment_safe_$($safe.Length)" (('sec' + 'ret="') + $asciiPad + $safe + $asciiPad + '"') 'assignment_secret' $false $utf8 }; Assert-DirectCase 'assignment_safe_unquoted' ('sec' + 'ret=PLACEHOLDER') 'assignment_secret' $false $utf8; Assert-DirectCase 'assignment_safe_near_miss' ('sec' + 'ret="prefix-redacted"') 'assignment_secret' $true $utf8; Assert-DirectCase 'assignment_angle_pairs' ('sec' + 'ret="<hidden><other>"') 'assignment_secret' $true $utf8; Write-Output 'assignment_quotes_boundaries'
    $encodedCases = [ordered]@{ provider_api_key=$positive; github_token=$github; aws_access_key=$aws; google_api_key=$google; slack_token=$slack; private_key=$private }; foreach ($entry in $encodedCases.GetEnumerator()) { Assert-DirectCase "encoded_base64_$($entry.Key)" ([Convert]::ToBase64String($utf8.GetBytes($entry.Value))) 'encoded_secret' $true $utf8 }
    $base64 = [Convert]::ToBase64String($utf8.GetBytes($positive)); $base64MaxText = ('x' * (3072-$positive.Length-5))+([char]0xFFFE)+"`n$positive`n"; $base64Max = [Convert]::ToBase64String($utf8.GetBytes($base64MaxText)); Assert-DirectCase 'encoded_base64_left_boundary' ('A'+$base64Max) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_base64_right_boundary' ($base64Max+'A') 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_base64_noncanonical' ($base64.Substring(0,$base64.Length-2)+([char]([int][char]$base64[$base64.Length-2]+1))+'=') 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_base64_utf8' ('/'*16) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_one_layer' ([Convert]::ToBase64String($utf8.GetBytes($base64))) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_direct_only' ([Convert]::ToBase64String($utf8.GetBytes((('api'+'_key=')+('q'*12))))) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_base64_max' $base64Max 'encoded_secret' $true $utf8; Assert-DirectCase 'encoded_base64_long' ([Convert]::ToBase64String($utf8.GetBytes($base64MaxText+'xxx'))) 'encoded_secret' $false $utf8
    $base64Url = [Convert]::ToBase64String($utf8.GetBytes(([char]0xFFFE)+"`n$positive`n"+([char]0xFFFE))).Replace('+','-').Replace('/','_'); $urlMaxText = ('x'*3041)+([char]0xFFFE)+"`n$positive`n"+([char]0xFFFE); $urlMax = [Convert]::ToBase64String($utf8.GetBytes($urlMaxText)).Replace('+','-').Replace('/','_'); Assert-DirectCase 'encoded_base64url_provider_api_key' $base64Url 'encoded_secret' $true $utf8; Assert-DirectCase 'encoded_base64url_max' $urlMax 'encoded_secret' $true $utf8; Assert-DirectCase 'encoded_base64url_long' ([Convert]::ToBase64String($utf8.GetBytes($urlMaxText+'xxx')).Replace('+','-').Replace('/','_')) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_base64url_left_boundary' ('_'+$urlMax) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_base64url_right_boundary' ($urlMax+'-') 'encoded_secret' $false $utf8; $pad=$base64Url.Length-$base64Url.TrimEnd('=').Length; $di=$base64Url.Length-$pad-1; Assert-DirectCase 'encoded_base64url_noncanonical' ($base64Url.Substring(0,$di)+([char]([int][char]$base64Url[$di]+1))+('='*$pad)) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_base64url_one_layer' ([Convert]::ToBase64String($utf8.GetBytes($base64Url)).Replace('+','-').Replace('/','_')) 'encoded_secret' $false $utf8
    $hex=[Convert]::ToHexString($utf8.GetBytes($positive)); $hexMaxText=('x'*(4096-$positive.Length-2))+"`n$positive`n"; $hexMax=[Convert]::ToHexString($utf8.GetBytes($hexMaxText)); Assert-DirectCase 'encoded_hex_provider_api_key' $hex.ToLowerInvariant() 'encoded_secret' $true $utf8; Assert-DirectCase 'encoded_hex_left_boundary' ('f'+$hexMax) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_hex_right_boundary' ($hexMax+'A') 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_hex_utf8' ('FF'*16) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_hex_one_layer' ([Convert]::ToHexString($utf8.GetBytes($hex))) 'encoded_secret' $false $utf8; Assert-DirectCase 'encoded_hex_max' $hexMax 'encoded_secret' $true $utf8; Assert-DirectCase 'encoded_hex_long' ([Convert]::ToHexString($utf8.GetBytes($hexMaxText+'x'))) 'encoded_secret' $false $utf8; Write-Output 'encodings_and_types'
    $fakeDir=Join-Path $sandbox 'fake'; $blobDir=Join-Path $fakeDir 'blobs'; [IO.Directory]::CreateDirectory($blobDir)|Out-Null; $env:FG_ROOT=$sandbox; $env:FG_BLOBS=$blobDir
    $fakeSource=@'
param([Parameter(ValueFromRemainingArguments=$true)][string[]]$A)
function O([byte[]]$B){$s=[Console]::OpenStandardOutput();$s.Write($B,0,$B.Length)}
$A=@($A)+@($args)
$c=$env:FG_CASE
if($A[0] -eq 'rev-parse'){if($c -eq 'root_fail'){exit 4};[Console]::WriteLine($env:FG_ROOT);exit 0}
if($A[0] -eq 'ls-files'){if($c -eq 'list_fail'){exit 5};$v=if($A -contains '--stage'){$env:FG_ROWS}else{$env:FG_PATHS};if($v){O ([Text.Encoding]::UTF8.GetBytes(($v -split '\|' -join "`0")+"`0"))};exit 0}
if($A[0] -eq 'cat-file'){if($c -eq 'cat_fail'){exit 6};O ([IO.File]::ReadAllBytes((Join-Path $env:FG_BLOBS ($A[2]+'.bin'))));exit 0}
exit 7
'@
    Set-Content -LiteralPath (Join-Path $fakeDir 'fake_git.ps1') -Value $fakeSource -Encoding utf8NoBOM; Set-Content -LiteralPath (Join-Path $fakeDir 'git.cmd') -Value "@echo off`r`n`"$PSHOME\pwsh.exe`" -NoProfile -File `"%~dp0fake_git.ps1`" %*" -Encoding ascii; $oldPath=$env:PATH; $env:PATH=$fakeDir+[IO.Path]::PathSeparator+$oldPath
    $oid1='1111111111111111111111111111111111111111'; $oid2='2222222222222222222222222222222222222222'; $clean=[byte[]]$utf8.GetBytes('ordinary public text'); $secret=[byte[]]$utf8.GetBytes($positive); $qpath='renamed name.txt'; [IO.File]::WriteAllBytes((Join-Path $sandbox $qpath),$secret)
    Set-FakeGit @($qpath) @("100644 $oid1 0`t$qpath") @{$oid1=$clean}; Assert-ExactResult (Invoke-Scanner @('-Tracked')) 2 @('{"source":"worktree","path":"renamed name.txt","rule":"provider_api_key"}') 'dirty_worktree'; Assert-ExactResult (Invoke-Scanner @('-Staged')) 0 @('CREDENTIAL_SCAN_PASS files=1') 'clean_index'
    [IO.File]::WriteAllBytes((Join-Path $sandbox $qpath),$clean); Set-FakeGit @($qpath) @("100644 $oid1 0`t$qpath") @{$oid1=$secret}; Assert-ExactResult (Invoke-Scanner @('-Staged')) 2 @('{"source":"index","path":"renamed name.txt","rule":"provider_api_key"}') 'staged_secret'; Assert-ExactResult (Invoke-Scanner @('-Tracked')) 0 @('CREDENTIAL_SCAN_PASS files=1') 'clean_worktree'
    [IO.File]::WriteAllBytes((Join-Path $sandbox $qpath),$secret); Set-FakeGit @($qpath) @("100755 $oid1 0`t$qpath") @{$oid1=$secret}; Assert-ExactResult (Invoke-Scanner @('-Tracked','-Staged')) 2 @('{"source":"index","path":"renamed name.txt","rule":"provider_api_key"}','{"source":"worktree","path":"renamed name.txt","rule":"provider_api_key"}') 'both_sources'; Write-Output 'staged_vs_worktree'
    [IO.File]::WriteAllBytes((Join-Path $sandbox 'first.png'),$clean); [IO.File]::WriteAllBytes((Join-Path $sandbox 'second.txt'),$clean); Set-FakeGit @('first.png','second.txt') @("100644 $oid1 0`tfirst.png","100755 $oid2 0`tsecond.txt") @{$oid1=[byte[]](0x00,0x61,0x00);$oid2=$secret}; Assert-ExactResult (Invoke-Scanner @('-Staged')) 2 @('{"source":"index","path":"second.txt","rule":"provider_api_key"}') 'binary_blob_separation'
    Set-FakeGit @('second.txt') @("100644 $oid1 1`tsecond.txt") @{$oid1=$clean}; Assert-OperationalFailure (Invoke-Scanner @('-Staged')) 'index_entry_failed' 'index' 'second.txt' 'zero_stage0'; Set-FakeGit @('second.txt') @("100644 $oid1 0`tsecond.txt","100644 $oid2 0`tsecond.txt") @{$oid1=$clean;$oid2=$clean}; Assert-OperationalFailure (Invoke-Scanner @('-Staged')) 'index_entry_failed' 'index' 'second.txt' 'two_stage0'
    Set-FakeGit @('second.txt') @("120000 $oid1 0`tsecond.txt") @{$oid1=$clean}; Assert-OperationalFailure (Invoke-Scanner @('-Staged')) 'index_mode_unsupported' 'index' 'second.txt' 'unsupported_mode'; Set-FakeGit @('second.txt') @("100644 $oid1 0`tsecond.txt") @{$oid1=$clean} 'cat_fail'; Assert-OperationalFailure (Invoke-Scanner @('-Staged')) 'read_failed' 'index' 'second.txt' 'cat_file_nonzero'; Write-Output 'index_modes_and_rename'
    Set-FakeGit @('second.txt') @() @{} 'root_fail'; Assert-OperationalFailure (Invoke-Scanner @('-Tracked')) 'git_root_failed' '' '' 'root_nonzero'; Set-FakeGit @('second.txt') @() @{} 'list_fail'; Assert-OperationalFailure (Invoke-Scanner @('-Tracked')) 'git_list_failed' 'worktree' '' 'list_nonzero'
    Set-FakeGit @('../outside.txt') @() @{}; Assert-OperationalFailure (Invoke-Scanner @('-Tracked')) 'path_escape' 'worktree' '../outside.txt' 'worktree_escape'; Set-FakeGit @('../outside.txt') @("100644 $oid1 0`t../outside.txt") @{$oid1=$clean}; Assert-OperationalFailure (Invoke-Scanner @('-Staged')) 'path_escape' 'index' '../outside.txt' 'index_escape'
    Set-FakeGit @('/absolute.txt') @() @{}; Assert-OperationalFailure (Invoke-Scanner @('-Tracked')) 'path_escape' 'worktree' '/absolute.txt' 'worktree_absolute'; Set-FakeGit @('nested/./second.txt') @("100644 $oid1 0`tnested/./second.txt") @{$oid1=$clean}; Assert-OperationalFailure (Invoke-Scanner @('-Staged')) 'path_escape' 'index' 'nested/./second.txt' 'index_not_normalized'
    Set-FakeGit @('missing.txt') @() @{}; Assert-OperationalFailure (Invoke-Scanner @('-Tracked')) 'read_failed' 'worktree' 'missing.txt' 'worktree_missing'; Set-FakeGit @('folder') @() @{}; Assert-OperationalFailure (Invoke-Scanner @('-Tracked')) 'not_regular_file' 'worktree' 'folder' 'worktree_directory'
    $target=Join-Path $sandbox 'target'; [IO.Directory]::CreateDirectory($target)|Out-Null; [IO.File]::WriteAllBytes((Join-Path $target 'clean.txt'),$clean); New-Item -ItemType Junction -Path (Join-Path $sandbox 'link') -Target $target|Out-Null; Set-FakeGit @('link/clean.txt') @() @{}; Assert-OperationalFailure (Invoke-Scanner @('-Tracked')) 'reparse_point' 'worktree' 'link/clean.txt' 'worktree_reparse'
    $textPaths = @('.gitignore','.gitattributes','.dockerignore','.python-version','.npmrc','Dockerfile','Makefile','LICENSE','NOTICE') + @('.md','.txt','.json','.jsonl','.toml','.yaml','.yml','.ini','.cfg','.conf','.env','.example','.py','.pyi','.js','.mjs','.cjs','.ts','.tsx','.jsx','.html','.css','.scss','.sql','.ps1','.psm1','.psd1','.sh','.bash','.cmd','.bat','.lock','.in' | ForEach-Object { 'allow' + $_ })
    $textRows = @($textPaths | ForEach-Object { "100644 $oid1 0`t$_" }); Set-FakeGit $textPaths $textRows @{$oid1=$clean}; Assert-ExactResult (Invoke-Scanner @('-Staged')) 0 @("CREDENTIAL_SCAN_PASS files=$($textPaths.Count)") 'text_allowlist'
    $binaryPaths = @('.png','.jpg','.jpeg','.gif','.webp','.pdf','.ico','.zip','.gz','.7z','.exe','.dll','.pyd','.so','.woff','.woff2','.ttf','.mp3','.mp4','.sqlite','.db' | ForEach-Object { 'skip' + $_ }); $binaryRows = @($binaryPaths | ForEach-Object { "100644 $oid1 0`t$_" }); Set-FakeGit $binaryPaths $binaryRows @{$oid1=[byte[]](0x00,0x61,0x00)}; Assert-ExactResult (Invoke-Scanner @('-Staged')) 0 @('CREDENTIAL_SCAN_PASS files=0') 'binary_skiplist'
    $env:PATH=$oldPath; $fresh=Join-Path $sandbox 'fresh'; [IO.Directory]::CreateDirectory((Join-Path $fresh 'scripts/tests'))|Out-Null; Copy-Item -LiteralPath $scanner -Destination (Join-Path $fresh 'scripts/bootstrap_scan_credentials.ps1'); Copy-Item -LiteralPath $PSCommandPath -Destination (Join-Path $fresh 'scripts/tests/bootstrap_scanner_contract.ps1')
    $git=(Get-Command git -CommandType Application -ErrorAction Stop | Select-Object -First 1).Source; & $git -C $fresh init --quiet 2>&1 | Out-Null; if($LASTEXITCODE){Stop-Contract 'fresh_git_init'}; & $git -C $fresh add -- scripts/bootstrap_scan_credentials.ps1 scripts/tests/bootstrap_scanner_contract.ps1 2>&1 | Out-Null; if($LASTEXITCODE){Stop-Contract 'fresh_git_add'}
    Push-Location $fresh; try { Assert-ExactResult (Invoke-Scanner @('-Tracked','-Staged')) 0 @('CREDENTIAL_SCAN_PASS files=4') 'fresh_repository_gate' } finally { Pop-Location }; Write-Output 'path_safety_and_errors'
    Assert-ExactResult (Invoke-Scanner @('-Path', '.\invalid.txt')) 3 @('{"code":"decode_failed","source":"path","path":"invalid.txt"}') 'redaction_error_order'
    $parseErrors = $null; $parseTokens = $null; $ast = [System.Management.Automation.Language.Parser]::ParseFile($scanner, [ref]$parseTokens, [ref]$parseErrors)
    if ($parseErrors.Count) { Stop-Contract 'redaction_ast_parse' }
    $catchNodes = @($ast.FindAll({ param($node) $node -is [System.Management.Automation.Language.CatchClauseAst] }, $true))
    $constantNodes = @($catchNodes | Where-Object { $_.Extent.Text -match "scan_failed" })
    if ($constantNodes.Count -ne 1) { Stop-Contract 'redaction_top_catch_count' }
    $topCatch = $constantNodes[0].Extent.Text
    if ($topCatch -notmatch "Write-ScanRecord\s+-Code\s+'scan_failed'\s*;\s*exit\s+3" -or $topCatch -match '\$|value|content|oid|Exception') { Stop-Contract 'redaction_top_catch_constant' }
    Write-Output 'redaction'
    Write-Output 'BOOTSTRAP_SCANNER_CONTRACT_PASS'
 } finally { $env:PATH=$oldPath; Pop-Location }
} finally { $link=Join-Path $sandbox 'link'; if (Test-Path -LiteralPath $link) { Remove-Item -LiteralPath $link -Force -ErrorAction SilentlyContinue }; if ([IO.Directory]::Exists($sandbox)) { Remove-Item -LiteralPath $sandbox -Recurse -Force } }
